name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Disable IPv6
        run: |
          sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1

      - name: Sync Files to Core Folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          security: loose
          local-dir: ./
          server-dir: laravel_app/
          state-name: .ftp-deploy-sync-state-app.json
          exclude: |
            **/.git*
            **/.git*/**
            public/**
            node_modules/**
            vendor/**

      - name: Sync Public Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          security: loose
          local-dir: public/
          server-dir: public_html/
          state-name: .ftp-deploy-sync-state-public.json
          exclude: |
            **/.git*
            index.php
            .htaccess